### PR TITLE
add lesscss support

### PR DESCRIPTION
**Pull request by basti1253**
Hi,

thanks for your great work. Would be great if you can merge that in.

best regards

Sebastian

### CODE REVIEW

**Comment by basti1253** [comment]
Screenshot:
screenshot

**Comment by HTD** [comment]
I'm not sure what am I doing wrong but I can't merge it. Git shows conflict but I have no idea what the conflict here is. Can you help me with this?

**Comment by basti1253** [comment]
Hi HTD,

no worries, I can apply these changes again to current master branch (so hopefully no merge conflict occurs). I can send you my IRC or jabber handle by PM if you need any further help.

best regards

Sebastian

**Comment by HTD** [comment]
It would be great if we could merge your changes to master to make project clear for other ppl to develop.

I currently don’t have time for NST development - too many different projects.

I would be glad if someone would take this project from me.

I have my reasons to leave ActiveState community for good. Let’s say creating the direct competition for Komodo Edit would be one of them 😊

Greetings,

A.

Sent from Windows Mail

From: Sebastian Sauer
Sent: ‎Tuesday‎, ‎December‎ ‎9‎, ‎2014 ‎11‎:‎39‎ ‎PM
To: HTD/NST
Cc: MaSzyna - Symulator Pojazdów Szynowych

Hi HTD,

no worries, I can apply these changes again to current master branch (so hopefully no merge conflict occurs). I can send you my IRC or jabber handle by PM if you need any further help.

best regards

Sebastian

**Pull request closed without merging**
