### PR TITLE
Added Komodo 9 support

### PR DESCRIPTION
**Pull request by Defman21**

### CODE REVIEW

**Comment by garak** [comment]
:+1:  please merge this!

**Comment by vita10gy** [comment]
Any progress on this? I miss this extension bad. :)

**Comment by abetkin** [comment]
I'm getting "(null) is incompatible with Komodo Edit 9.0.1"

**Comment by torstenberg** [comment]
Just edit the file install.rdf and change the line

em:maxVersion8.*/em:maxVersion

to 

em:maxVersion9.*/em:maxVersion

and reinstall the plugin. Then it works. You can just do this in your local copy, then you do not need to wait until someone updates the code here on github.

**Comment by abetkin** [comment]
[2015-04-22 13:16:37,883] [ERROR] console-logger: TypeError: installs[0].addon is null (2) in chrome://komodo/content/extmgr/em-overlay.js:124
Traceback (most recent call last):
  File "chrome://komodo/content/extmgr/em-overlay.js", line 124, in

**Comment by abetkin** [comment]
[2015-04-22 13:33:58,451] [ERROR] console-logger: TypeError: installs[0].addon is null (2) in chrome://komodo/content/extmgr/em-overlay.js:124
Traceback (most recent call last):
  File "chrome://komodo/content/extmgr/em-overlay.js", line 124, in

**Pull request closed without merging**
