### PR TITLE
Sets a correct "focus behaviour" when the application starts.

### PR DESCRIPTION
**Pull request by titoBouzout**
Hi there!
This, properly setups the correct selection behavior on startup. 
When nst tab was selected on close, will opens selected on start.
When nst tab was closed on app close, will open closed. 

Users ( like me ) don't like the changes of focus forced by app/ext.

Regards,

### CODE REVIEW

**Comment by titoBouzout** [comment]
I've added another commit that fix a bug of the tree not refreshing when the tab change from closed to open. I also suggested this same fix on forum sometime ago.

offtopic: I'm not sure if github accepts two different commits as two different pull request :? I don't see any option. sorry

Regards

**Comment by HTD** [comment]
I've fixed it - first - I think tab persistance should not be set in XUL. I don't know why, but on my Komodo nightly build it just crashes while last active tab is "Source". It helps when I delete localstore.rdf, but only for one restart.

I've noticed Komodo stores NST_tab checked state, but I don't know what it does with toolbox2_tab checked state. They are checked both and none of them work (it can be reset manually from code).

Enough. I moved persistence to main initialisation code, where it works as expected. I've fixed 2 lesser bugs in XUL, there was "_" instead of "." after "uilayout" (twice, weird), and NST_tab was inserted after "codebrowser_tab" instead of "toolbox2_tab". Tested, works. Now, if I only find time to add SQL support we can upload it to Activestate as new release.

**Comment by titoBouzout** [comment]
Thanks for looking at this, much appreciated.

Persistence works as expected after deleting localstore.rdf.

The other issue, the tab is not updated, when you open a file, and then open the tab.
Steps to reproduce:
1 - open a file with NST opened. ( NST updates content for opened file )
2 - close NST
3 - Open another file.
4 - Now open NST

The NST content is still showing the content of the previous file. Not the file that is on focus.

I think this is because you removed the onfocus="" that I submited.
https://github.com/titoBouzout/NST/commit/843a670b696a6f36c1a42e8ae4895968498ed272

Regards,

**Comment by HTD** [comment]
OK, fixed :)

Focus is attached later, in line 1656 of NST.js.
I've noticed some things go wrong if we touch some of
the events too early, before overlay is merged.

This is about to change with 7.x style xul, but
I have no time to implement it now.

There's a way to make it compatible with both
Komodo 6.x and 7.x but I haven't figured out
how to do it yet.

On Wed, 21 Sep 2011 04:06:43 +0200, Roberto Bouzout (tito)  
reply@reply.github.com  
wrote:

> Thanks for looking at this, much appreciated.
> 
> Persistence works as expected after deleting localstore.rdf.
> 
> The other issue, the tab is not updated, when you open a file, and then  
> open the tab.
> Steps to reproduce:
> 1 - open a file with NST opened. ( NST updates content for opened file )
> 2 - close NST
> 3 - Open another file.
> 4 - Now open NST
> 
> The NST content is still showing the content of the previous file. Not  
> the file that is on focus.
> 
> I think this is because you removed the onfocus="" that I submited.
> https://github.com/titoBouzout/NST/commit/843a670b696a6f36c1a42e8ae4895968498ed272
> 
> Regards,

## 

Używam klienta poczty Opera Mail: http://www.opera.com/mail/

**Comment by HTD** [comment]
Hello,

Please check the latest source, all initialization is rewritten.
I double checked it works and handles moving NST tab between left and 
right panels properly and fast.

It uses TweakUI mechanism for this, so you need this installed to see 
how it works.

Default, without TweakUI, NST shows on the right.

If you won't find any blocking bugs, I think I should release it,
two major bugs fixed (the other one was triggered by opening new Komodo 
project in new window).

Oh, it can misbehave on first run. It should work perfectly on clean 
Komodo install, but if there are some garbage from previous versions,
you just need to restart Komodo once with new version and it should be 
fixed. You don't have to remove localstore.rdf anymore.

Cheers,
Adam

**Comment by titoBouzout** [comment]
I checked quickly and focus seems to works as expected.

I don't have TweakUI installed.

Just one little issue. Toggling some option like "sort order" or "automatic location" throws
this._updateIcons is not a function in line 1620 of chrome://nst/content/NST.js.

Regards

**Pull request merged**
