### PR TITLE
added c++ support

### PR DESCRIPTION
**Pull request by sni**
Hi,

I added support for C++.

Thanks for your work,
 Sven

### CODE REVIEW

**Comment by HTD** [comment]
Hello.

I've tested C++ support with Mozilla's StartupCache.cpp
file, and I think something is wrong.

The same with plain C (Audacious sources, main.c).

Only one function was mapped, while I saw more in code.

Since I don't speak C well enough, it would be
great if you take a look at it.

I think it breaks when there's a newline after
function return type, so the parser should store
previous non-empty line and use it to match functions.

Of course it should use it only if it does contain
only keyword characters (for speed).

It should also make use of "static" and other such
keywords, we have icons for those.
(public|private|protected( static)?)

Cheers,
Adam

> Hi,
> 
> I added support for C++.
> 
> Thanks for your work,
>   Sven
> 
> You can merge this Pull Request by running:
> 
>    git pull https://github.com/sni/NST testing
> 
> Or you can view, comment on it, or merge it online at:
> 
>    https://github.com/HTD/NST/pull/1
> 
> -- Commit Summary --
> - added c++ support
> 
> -- File Changes --
> 
> M content/NST.js (9)
> 
> -- Patch Links --
> 
>    https://github.com/HTD/NST/pull/1.patch
>    https://github.com/HTD/NST/pull/1.diff

**Comment by sni** [comment]
Hi Adam,

Could you send me your 2 testfiles, then i will have a look.

Thanks,
  Sven

**Comment by HTD** [comment]
On Thu, 08 Sep 2011 15:41:21 +0200, Sven Nierlein  
reply@reply.github.com  
wrote:

> Hi Adam,
> 
> Could you send me your 2 testfiles, then i will have a look.
> 
> Thanks,
>   Sven

## 

Using Opera's revolutionary email client: http://www.opera.com/mail/

**Comment by sni** [comment]
Seems like it is not possible to add full and general C++ support easily. There are way to much ways to create functions
in C/C++. In theory, you could create function definitons over several lines which makes parsing for a line-by-line parser
very difficult.

**Comment by HTD** [comment]
I always thought it's like this:

keyword identifier ( some_identifiers ) { } or
keyword identifier::identifier ( some_identifiers ) { }

You can replace space character with any number and kind of whitespace 
characters, including newlines. (BTW, it's done like this in PHP and JS)
Line by line parser can track previous lines if they match specified 
conditions.

If there are more ways to define functions, please point me to some 
sources where I can find them.

"The impossible will take a little time" :)

Cheers,
Adam

> Seems like it is not possible to add full and general C++ support easily. There are way to much ways to create functions
> in C/C++. In theory, you could create function definitons over several lines which makes parsing for a line-by-line parser
> very difficult.

**Pull request merged**
